### ISSUE TITLE
License

### ISSUE THREAD

**Issue by iceblue25** [fhucho/ctex#1]
Thanks for the nice package. Does it have a permissive license?

**Comment by fhucho** [comment]
Yes, you can use it howecer you want.

**Comment by iceblue25** [comment]
Thanks for the reply. For lawyers to allow to use it,  it needs a license associated like this package has a license here https://github.com/lostanlen/WaveletScattering.jl/blob/master/LICENSE . 
Thanks for the work I was used  too to not attach a license to my work but if a license does not exist no one will use it other than personal use.

**Comment by fhucho** [comment]
If you submit a pull request with the license file, I'll accept it.

**Comment by iceblue25** [comment]
Thanks, added a  MIT license and submitted a PR. Add your name next to the copyright year as a copyright holder if you like.
